name: 'esbuild-http-import'
description: 'GitHub Action for ESBuild with support for HTTP Imports'
branding:
  icon: 'box'  
  color: 'black'
inputs:
  entryPoint:  
    description: 'The main entry point'
    required: false
    default: './index.js'
  outfile: 
    description: 'The name of the output file'
    required: false
    default: './dist/index.js'
outputs:
  bundle: 
    description: 'the output file'
runs:
  using: 'node16'
  main: './index.js'
